workflows:
  android-workflow:
    name: Android Workflow
    environment:
      groups:
        - keystore_credentials # Optional, for signing the APK
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    scripts:
      - name: Set up environment
        script: |
          echo "Setting up environment..."
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
      - name: Build Android app
        script: |
          echo "Building Android app..."
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
